### ISSUE TITLE
Issue with username when editing an item

### ISSUE THREAD

**Issue by mayel** [mayel/LETS-app#5]
For eg. in edit offer shows the user field contains [Object] instead of the name

**Comment by mayel** [comment]
@matslats 
can we also clarify/standardise what get’s sent in POST (item creation or edit) for payee/payer, maybe best would be the numerical user_id to keep it consistent

apart from transactions, do we really need to have a user field though? shouldn’t it be assumed that it’s the logged in user?

for now, I made the field appear but disabled.

**Comment by matslats** [comment]
I don't understand.
The user field should appear as an editable field only to admins because a user cannot transfer ownership if their offer to somebody else. Today I've been working on permissions so maybe this issue will go away.
The system expects new items to be POSTed and existing items to be PATCHed. I don't know how we got this far if there's any ambiguity about that.

**Comment by matslats** [comment]
Now I've pushed the updates.
When you run the OPTIONS on a specific offer you should only see the user_id field if you are admin
